image: cfme_gitlabci:5.5.z
before_script:
  - su postgres -c ". /docker-environment.sh && pg_ctl start -w -D /var/opt/rh/rh-postgresql94/lib/pgsql/data/"
  - ruby -v
  - postgres --version
  - bundle config --global jobs 3
  - bundle config --global retry 3
  - echo "1" > REGION
  - cp certs/v2_key.dev certs/v2_key
  - cp config/database.pg.yml config/database.yml
  - export BUNDLE_GEMFILE=$PWD/Gemfile
test:vmdb:
  script:
    - bundle update
    - bundle exec rake test:vmdb:setup
    - bundle exec rake test:vmdb
test:automation:
  script:
    - bundle update
    - bundle exec rake test:automation:setup
    - bundle exec rake test:automation
test:migrations:
  script:
    - bundle update
    - bundle exec rake test:migrations:setup
    - bundle exec rake test:migrations
test:spu_ui-self_service:
  script:
    - bundle update
    - pushd spa_ui/self_service
    - npm install bower gulp -g
    - npm install
    - bower install --allow-root --config.analytics=false # Due to running in a privileged comtainer
    - gulp build
    - npm version
    - popd
    - bundle exec rake test:self_service:setup
    - bundle exec rake test:self_service
test:brakeman:
  script:
    - bundle update
    - bundle exec rake test:brakeman:setup
    - bundle exec rake test:brakeman
test:replication:
  script:
    - bundle update
    - bundle exec rake test:replication:setup
    - bundle exec rake test:replication
test:gem-pending:
  script:
    - cd gems/pending
    - export BUNDLE_GEMFILE=$PWD/Gemfile
    - bundle update
    - bundle exec rake
test:javascript:
  script:
    - bundle update
    - bundle exec rake test:javascript:setup
    - bundle exec rake test:javascript
test:gem-manageiq_foreman:
  script:
    - cd gems/manageiq_foreman
    - export BUNDLE_GEMFILE=$PWD/Gemfile
    - bundle update
    - bundle exec rake
